# Generated by Django 5.1.6 on 2025-03-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mijoz_qarz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mijoz',
            name='bolim',
        ),
    ]
